site_name: David's Pekora Trading Guide
repo_url: https://github.com/dxamima/pekora-trading-guide
theme:
  name: material
  favicon: site/img/favicon.ico
  logo: site/img/favicon.ico
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

plugins:
  - social